name: GitHub Actions Demo
run-name: ${{ github.actor}} is testing out GitHub Actions
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Report triggering event
              run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
            - name: Segundo Step do fluxo
              run: echo "A ação está sendo gerado no Sistema Operacional ${{ runner.os }}."
            - name: Terceiro Step do fluxo
              run: echo "O repositório que está sendo utilizado é o ${{ github.repository }}."
            - name: Último Step do fluxo
              run: echo "Criado em 14/09/2026."